### ISSUE TITLE
Crash while parsing a generic type parameter on a type alias

### ISSUE THREAD

**Issue by EclipseOnFire** [personio/kotlin-auto-formatter#7]
Hi,

I'm getting the following error:
```
org.kotlin.formatter.scanning.nodepattern.NodeSequenceNotMatchedException: Could not match node sequence [KDoc, PsiWhiteSpace, PsiElement(typealias), PsiWhiteSpace, PsiElement(IDENTIFIER), Element(TYPE_PARAMETER_LIST), PsiWhiteSpace, PsiElement(EQ), PsiWhiteSpace, Element(TYPE_REFERENCE)]
	at org.kotlin.formatter.scanning.nodepattern.NodePattern.matchSequence(NodePattern.kt:44)
	at org.kotlin.formatter.scanning.TypealiasScanner.scan(TypealiasScanner.kt:44)
	at org.kotlin.formatter.scanning.KotlinScanner.scanInState$formatter(KotlinScanner.kt:47)
	at org.kotlin.formatter.scanning.KotlinScanner.scanSingleNode(KotlinScanner.kt:80)
	at org.kotlin.formatter.scanning.KotlinScanner.access$scanSingleNode(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.KotlinScanner$scanNodes$1.invoke(KotlinScanner.kt:58)
	at org.kotlin.formatter.scanning.KotlinScanner$scanNodes$1.invoke(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.KotlinScanner$nodePattern$1$1$2$1.invoke(KotlinScanner.kt:69)
	at org.kotlin.formatter.scanning.KotlinScanner$nodePattern$1$1$2$1.invoke(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:201)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:181)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.FinalPathStep.runActions(NodePattern.kt:150)
	at org.kotlin.formatter.scanning.nodepattern.NodePattern.matchSequence(NodePattern.kt:43)
	at org.kotlin.formatter.scanning.KotlinScanner.scanNodes$formatter(KotlinScanner.kt:59)
	at org.kotlin.formatter.scanning.KotlinScanner.scanNodes$formatter$default(KotlinScanner.kt:58)
	at org.kotlin.formatter.scanning.BlockScanner$nodePattern$1$2$2.invoke(BlockScanner.kt:31)
	at org.kotlin.formatter.scanning.BlockScanner$nodePattern$1$2$2.invoke(BlockScanner.kt:16)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:201)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:181)
	at org.kotlin.formatter.scanning.nodepattern.StateKt$andThen$1.invoke(State.kt:149)
	at org.kotlin.formatter.scanning.nodepattern.StateKt$andThen$1.invoke(State.kt)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.FinalPathStep.runActions(NodePattern.kt:150)
	at org.kotlin.formatter.scanning.nodepattern.NodePattern.matchSequence(NodePattern.kt:43)
	at org.kotlin.formatter.scanning.BlockScanner.scan(BlockScanner.kt:41)
	at org.kotlin.formatter.scanning.KotlinScanner.scanInState$formatter(KotlinScanner.kt:47)
	at org.kotlin.formatter.scanning.KotlinScanner.scanSingleNode(KotlinScanner.kt:80)
	at org.kotlin.formatter.scanning.KotlinScanner.access$scanSingleNode(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.KotlinScanner$scanNodes$1.invoke(KotlinScanner.kt:58)
	at org.kotlin.formatter.scanning.KotlinScanner$scanNodes$1.invoke(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.KotlinScanner$nodePattern$1$1$2$1.invoke(KotlinScanner.kt:69)
	at org.kotlin.formatter.scanning.KotlinScanner$nodePattern$1$1$2$1.invoke(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:201)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:181)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.FinalPathStep.runActions(NodePattern.kt:150)
	at org.kotlin.formatter.scanning.nodepattern.NodePattern.matchSequence(NodePattern.kt:43)
	at org.kotlin.formatter.scanning.KotlinScanner.scanNodes$formatter(KotlinScanner.kt:59)
	at org.kotlin.formatter.scanning.KotlinScanner.scanNodes$formatter$default(KotlinScanner.kt:58)
	at org.kotlin.formatter.scanning.SimpleScanner.scan(SimpleScanner.kt:13)
	at org.kotlin.formatter.scanning.KotlinScanner.scanInState$formatter(KotlinScanner.kt:47)
	at org.kotlin.formatter.scanning.KotlinScanner.scanSingleNode(KotlinScanner.kt:80)
	at org.kotlin.formatter.scanning.KotlinScanner.access$scanSingleNode(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.KotlinScanner$scanNodes$1.invoke(KotlinScanner.kt:58)
	at org.kotlin.formatter.scanning.KotlinScanner$scanNodes$1.invoke(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.KotlinScanner$nodePattern$1$1$2$1.invoke(KotlinScanner.kt:69)
	at org.kotlin.formatter.scanning.KotlinScanner$nodePattern$1$1$2$1.invoke(KotlinScanner.kt:28)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:201)
	at org.kotlin.formatter.scanning.nodepattern.Evaluation$Companion$consumingAction$1.invoke(State.kt:181)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.ContinuingPathStep.runActions(NodePattern.kt:136)
	at org.kotlin.formatter.scanning.nodepattern.FinalPathStep.runActions(NodePattern.kt:150)
	at org.kotlin.formatter.scanning.nodepattern.NodePattern.matchSequence(NodePattern.kt:43)
	at org.kotlin.formatter.scanning.KotlinScanner.scanNodes$formatter(KotlinScanner.kt:59)
	at org.kotlin.formatter.scanning.KotlinScanner.scanNodes$formatter$default(KotlinScanner.kt:58)
	at org.kotlin.formatter.scanning.SimpleScanner.scan(SimpleScanner.kt:13)
	at org.kotlin.formatter.scanning.KotlinScanner.scanInState$formatter(KotlinScanner.kt:47)
	at org.kotlin.formatter.scanning.KotlinScanner.scan(KotlinScanner.kt:36)
	at org.kotlin.formatter.KotlinFormatter.format(KotlinFormatter.kt:47)
	... 102 more
```

While parsing the following code:
```kotlin
typealias AlertComputationFunction<T> = (value: T, changeDate: Instant) -> Alert?
```

The crash seems to be caused by the generic parameter.

**Comment by hovinen** [comment]
Thanks for reporting this!

I'm pushing a fix and will do a new release this evening to address the issue.
